# Generated by Django 2.2.12 on 2020-04-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buzzword",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=127)),
                ("count", models.PositiveSmallIntegerField(blank=True, default=0)),
            ],
        ),
    ]
